### ISSUE TITLE
Estas a muy poco de terminar!

### ISSUE THREAD

**Issue by danmt** [jos311/hbd-bootcamp#1]
El archivo polyfills puede ir en la carpeta raiz del proyecto sin problema, pero las referencias a el deben apuntar a esa ubicacion. La app no debe correr al ejecutar `nx serve`, para arreglarlo puedes mover el archivo polyfills a la carpeta `src` o arreglar las referencias en project.json y tsconfig.app.json para que apunten a la ubicacion correcta.

**Comment by jos311** [comment]
Gracias mano! lo movi a la carpeta src... error de rookie! 😁

**Comment by danmt** [comment]
No te preocupes!! Ya estas aprobadoo
